### ISSUE TITLE
I'm stuck on the code. 

### ISSUE THREAD

**Issue by NikCasar** [NikCasar/stylish-beets#1]
I'm not sure what is wrong and I can't figure out what marker bot is trying to tell me to fix. 
@thomasjbradley

**Comment by thomasjbradley** [comment]
Let’s start with 2 things:

1. Fix the broken image—it doesn’t even exist in your folder
2. *Never* set the primary font-size to anything smaller than `100%`
https://github.com/NikCasar/stylish-beets/blob/gh-pages/css/main.css#L6
